export const ERROR = 'ERROR';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_RESTAURANT_DETAILS = 'FETCH_RESTAURANT_DETAILS';
export const LOAD_QUERY_PARAMS = 'LOAD_QUERY_PARAMS';
export const VISIBLE_FILTER_FORM = 'VISIBLE_FILTER_FORM';
